version: "3"
services:
  front:
    container_name: front
    restart: always
    build: ./front-end
    ports:
      - "8080:8080"
    links:
      - back
    depends_on:
      - back
  back:
    container_name: back
    restart: always
    build: ./back-end
    ports:
      - "3000:3000"
  db:
    container_name: db
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
    volumes:
      - ./mongoData:/data/db
    ports:
      - "27017:27017"
    command: mongod --auth